"""Self-contained HTML reports.

A backtest produces a wall of numbers, and the one thing you actually want to
look at — the shape of the equity curve against the thing it is supposed to beat
— is the one thing a terminal cannot show. This module renders that.

Everything is inlined: the SVG is generated here, the styles and the twenty
lines of tooltip JavaScript are in the file, and nothing is fetched from a CDN.
That is not minimalism for its own sake. The same function becomes Phase 4's
daily summary, emailed off a VPS with no browser and possibly no outbound
network, and a report that needs the internet to render is a report that will be
blank on the morning you most want to read it.

Colours come from the validated palette in the `dataviz` skill: categorical
slots 1 and 2 (blue, orange), which clear the colour-vision-deficiency and
contrast gates in both light and dark mode. The two series are also directly
labelled at the right-hand end, so identity never rests on hue alone.
"""

from __future__ import annotations

import html
import json
from dataclasses import dataclass
from functools import cache
from importlib import resources
from pathlib import Path

import numpy as np
import pandas as pd

from ai_finance.backtest.metrics import BacktestResult

#: Points kept when drawing a curve. Beyond this the SVG grows without the
#: picture changing.
MAX_POINTS = 600

_STRATEGY_COLOR = "var(--series-1)"
_BENCHMARK_COLOR = "var(--series-2)"


@dataclass(frozen=True)
class Stat:
    """One figure in the headline row."""

    label: str
    value: str
    note: str = ""
    tone: str = "neutral"  # neutral | good | bad


def write_report(
    result: BacktestResult,
    path: str | Path,
    *,
    title: str | None = None,
    subtitle: str = "",
    notes: list[str] | None = None,
) -> Path:
    """Render ``result`` to a standalone HTML file and return its path."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        _document(
            result,
            title=title or f"{result.strategy_name} on {result.symbol}",
            subtitle=subtitle,
            notes=notes or [],
        ),
        encoding="utf-8",
    )
    return path


# --------------------------------------------------------------------------- #
# document
# --------------------------------------------------------------------------- #


def _document(result: BacktestResult, *, title: str, subtitle: str, notes: list[str]) -> str:
    equity = _downsample(result.equity_curve)
    benchmark = _downsample(result.benchmark_curve)
    drawdown = _downsample(_drawdown_of(result.equity_curve))
    benchmark_drawdown = _downsample(_drawdown_of(result.benchmark_curve))

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)}</title>
<style>{_asset("report.css")}</style>
</head>
<body>
<main class="viz-root">
  <header>
    <h1>{html.escape(title)}</h1>
    <p class="sub">{html.escape(subtitle)}</p>
  </header>

  <section class="stats">{_stat_tiles(result)}</section>

  <section class="chart">
    <h2>Equity</h2>
    <p class="caption">What the strategy did to the account, against holding the
      asset and doing nothing. The benchmark pays no fees, which makes it a
      deliberately hard bar.</p>
    {_legend()}
    {_line_chart(equity, benchmark, "equity", money=True)}
  </section>

  <section class="chart">
    <h2>Drawdown</h2>
    <p class="caption">Distance below the previous peak. This is the number that
      decides whether a strategy is livable, not the return.</p>
    {_legend()}
    {_line_chart(drawdown, benchmark_drawdown, "drawdown", money=False, percent=True)}
  </section>

  <section class="chart">
    <h2>Where the money went</h2>
    {_cost_table(result)}
  </section>

  <section class="chart">
    <h2>Trades</h2>
    {_trade_table(result)}
  </section>

  {_notes_block(notes)}

  <footer>
    <p>Generated by AI_Finance. Costs modelled at
      {result.costs.round_trip_cost * 10_000:.1f} bp per round trip
      ({html.escape(result.costs.describe())}).</p>
  </footer>
</main>
<script>{_asset("report.js")}</script>
</body>
</html>
"""


def _notes_block(notes: list[str]) -> str:
    if not notes:
        return ""
    items = "".join(f"<li>{html.escape(note)}</li>" for note in notes)
    return (
        '<section class="notes">'
        "<h2>Read this before believing any of it</h2>"
        f"<ul>{items}</ul></section>"
    )


def _stat_tiles(result: BacktestResult) -> str:
    beat = result.excess_return > 0
    risk_adjusted = result.beat_benchmark_risk_adjusted
    stats = [
        Stat(
            "Return",
            _pct(result.total_return),
            "after all costs",
            "good" if result.total_return > 0 else "bad",
        ),
        Stat("Benchmark", _pct(result.benchmark_return), "buy and hold, cost-free"),
        Stat(
            "Excess",
            _pct(result.excess_return),
            result.benchmark_verdict.lower(),
            "good" if beat else "bad",
        ),
        Stat(
            "Sharpe",
            _num(result.sharpe),
            f"benchmark {_num(result.benchmark_sharpe)}",
            "good" if risk_adjusted else "bad",
        ),
        Stat(
            "Max drawdown",
            _pct(result.max_drawdown),
            f"benchmark {_pct(result.benchmark_max_drawdown)}",
        ),
        # Unsigned: a cost is not a gain, and "+2.41%" reads like one.
        Stat("Cost drag", _rate(result.cost_drag), "of starting capital", "bad"),
    ]
    return "".join(
        f'<div class="tile tone-{s.tone}">'
        f'<div class="tile-label">{html.escape(s.label)}</div>'
        f'<div class="tile-value">{html.escape(s.value)}</div>'
        f'<div class="tile-note">{html.escape(s.note)}</div></div>'
        for s in stats
    )


def _legend() -> str:
    return (
        '<div class="legend">'
        f'<span class="key"><i style="background:{_STRATEGY_COLOR}"></i>Strategy</span>'
        f'<span class="key"><i style="background:{_BENCHMARK_COLOR}"></i>Buy and hold</span>'
        "</div>"
    )


def _cost_table(result: BacktestResult) -> str:
    rows = [
        ("Exchange fees", f"{result.total_fees:,.2f}"),
        ("Spread and slippage", f"{result.total_price_concession:,.2f}"),
        ("Total cost", f"{result.total_costs:,.2f}"),
        ("As a share of starting capital", _pct(result.cost_drag)),
        ("Notional traded", f"{result.turnover:.1f}x starting capital"),
        ("Fills", f"{result.n_fills:,}"),
    ]
    return _table(["", "Amount"], rows)


def _trade_table(result: BacktestResult) -> str:
    rows = [
        ("Completed round trips", f"{result.n_trades:,}"),
        ("Win rate", _rate(result.win_rate)),
        ("Average win", f"{result.avg_win:+,.2f}"),
        ("Average loss", f"{result.avg_loss:+,.2f}"),
        ("Profit factor", _num(result.profit_factor)),
        ("Time holding a position", _rate(result.exposure)),
    ]
    return _table(["", "Value"], rows)


def _table(headers: list[str], rows: list[tuple[str, str]]) -> str:
    head = "".join(f"<th>{html.escape(h)}</th>" for h in headers)
    body = "".join(
        f"<tr><td>{html.escape(label)}</td><td class='num'>{html.escape(value)}</td></tr>"
        for label, value in rows
    )
    return f"<table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table>"


# --------------------------------------------------------------------------- #
# chart
# --------------------------------------------------------------------------- #


def _line_chart(
    primary: pd.Series,
    secondary: pd.Series,
    chart_id: str,
    *,
    money: bool,
    percent: bool = False,
) -> str:
    """Two-series line chart as inline SVG, with a shared crosshair tooltip."""
    width, height = 1000.0, 320.0
    left, right, top, bottom = 68.0, 96.0, 16.0, 34.0
    plot_w, plot_h = width - left - right, height - top - bottom

    values = np.concatenate([primary.to_numpy(float), secondary.to_numpy(float)])
    values = values[np.isfinite(values)]
    low, high = (float(values.min()), float(values.max())) if len(values) else (0.0, 1.0)
    ticks = _nice_ticks(low, high)
    axis_low, axis_high = ticks[0], ticks[-1]
    span = axis_high - axis_low or 1.0

    times = primary.index
    n = len(times)

    def x_of(i: int) -> float:
        return left + (plot_w * i / max(n - 1, 1))

    def y_of(value: float) -> float:
        return top + plot_h * (1.0 - (value - axis_low) / span)

    grid = "".join(
        f'<line class="grid" x1="{left:.1f}" x2="{left + plot_w:.1f}" '
        f'y1="{y_of(t):.1f}" y2="{y_of(t):.1f}"/>'
        f'<text class="tick" x="{left - 10:.1f}" y="{y_of(t) + 4:.1f}" '
        f'text-anchor="end">{_axis_label(t, money, percent)}</text>'
        for t in ticks
    )

    date_positions = np.linspace(0, n - 1, min(6, n)).astype(int)
    date_axis = "".join(
        f'<text class="tick" x="{x_of(int(i)):.1f}" y="{height - 10:.1f}" '
        f'text-anchor="middle">{times[int(i)]:%b %Y}</text>'
        for i in date_positions
    )

    primary_path = _path(primary.to_numpy(float), x_of, y_of)
    secondary_path = _path(secondary.to_numpy(float), x_of, y_of)

    baseline = ""
    if axis_low < 0 < axis_high:
        baseline = (
            f'<line class="baseline" x1="{left:.1f}" x2="{left + plot_w:.1f}" '
            f'y1="{y_of(0.0):.1f}" y2="{y_of(0.0):.1f}"/>'
        )

    last_primary = float(primary.iloc[-1])
    last_secondary = float(secondary.iloc[-1])
    labels = (
        f'<text class="direct" x="{left + plot_w + 8:.1f}" y="{y_of(last_primary) + 4:.1f}">'
        f"{_axis_label(last_primary, money, percent)}</text>"
        f'<text class="direct" x="{left + plot_w + 8:.1f}" y="{y_of(last_secondary) + 4:.1f}">'
        f"{_axis_label(last_secondary, money, percent)}</text>"
    )

    payload = json.dumps(
        {
            "dates": [t.strftime("%Y-%m-%d %H:%M") for t in times],
            "primary": [_round(v) for v in primary.to_numpy(float)],
            "secondary": [_round(v) for v in secondary.to_numpy(float)],
            "left": left,
            "plotW": plot_w,
            "money": money,
            "percent": percent,
        }
    )

    return f"""<figure class="figure" data-chart='{html.escape(payload, quote=True)}'>
  <svg viewBox="0 0 {width:.0f} {height:.0f}" preserveAspectRatio="none"
       role="img" aria-label="Strategy equity against buy and hold">
    {grid}{baseline}
    <path class="series-2" d="{secondary_path}"/>
    <path class="series-1" d="{primary_path}"/>
    {labels}{date_axis}
    <line class="crosshair" y1="{top:.1f}" y2="{top + plot_h:.1f}" style="display:none"/>
    <circle class="dot dot-1" r="4" style="display:none"/>
    <circle class="dot dot-2" r="4" style="display:none"/>
    <rect class="hit" x="{left:.1f}" y="{top:.1f}"
          width="{plot_w:.1f}" height="{plot_h:.1f}" fill="transparent"/>
  </svg>
  <div class="tooltip" hidden></div>
</figure>"""


def _path(values: np.ndarray, x_of, y_of) -> str:
    parts: list[str] = []
    drawing = False
    for i, value in enumerate(values):
        if not np.isfinite(value):
            drawing = False
            continue
        command = "L" if drawing else "M"
        parts.append(f"{command}{x_of(i):.1f},{y_of(float(value)):.1f}")
        drawing = True
    return " ".join(parts)


def _drawdown_of(curve: pd.Series) -> pd.Series:
    return curve / curve.cummax() - 1.0


def _downsample(series: pd.Series, limit: int = MAX_POINTS) -> pd.Series:
    """Thin a curve for drawing, always keeping the first and last points."""
    if len(series) <= limit:
        return series
    positions = np.unique(np.linspace(0, len(series) - 1, limit).astype(int))
    return series.iloc[positions]


def _nice_ticks(low: float, high: float, target: int = 5) -> list[float]:
    """Round tick values spanning ``[low, high]``."""
    if not np.isfinite(low) or not np.isfinite(high) or high <= low:
        return [0.0, 1.0]
    raw = (high - low) / target
    magnitude = 10.0 ** np.floor(np.log10(raw))
    for multiple in (1.0, 2.0, 2.5, 5.0, 10.0):
        step = magnitude * multiple
        if raw <= step:
            break
    start = np.floor(low / step) * step
    stop = np.ceil(high / step) * step
    count = round((stop - start) / step) + 1
    return [start + i * step for i in range(count)]


def _axis_label(value: float, money: bool, percent: bool) -> str:
    if percent:
        return f"{value * 100:.0f}%"
    if money:
        return f"{value:,.0f}"
    return f"{value:.2f}"


def _round(value: float) -> float | None:
    return None if not np.isfinite(value) else round(float(value), 4)


def _pct(value: float) -> str:
    return "n/a" if not np.isfinite(value) else f"{value * 100:+.2f}%"


def _rate(value: float) -> str:
    return "n/a" if not np.isfinite(value) else f"{value * 100:.1f}%"


def _num(value: float) -> str:
    return "n/a" if not np.isfinite(value) else f"{value:.2f}"


@cache
def _asset(name: str) -> str:
    """Read a stylesheet or script from the package.

    Kept as real files rather than string literals so they can be edited with
    CSS and JavaScript tooling, and so the Python linter is not asked to hold
    opinions about stylesheet line length. They are inlined into the output at
    render time, which is what keeps the report a single portable file.
    """
    return resources.files("ai_finance.assets").joinpath(name).read_text(encoding="utf-8")
